[package]
name = "python-uuids"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
rand = "0.9.0-alpha.2"
uuid = { version = "1.10.0", features = ["v4"] }
libc = "0.2.155"
md5 = "0.7.0"
sha1 = "0.11.0-pre.4"
